name: Generate package-lock.json

on:
  workflow_dispatch:

permissions:
  contents: write   # 🔥 This is the fix!
  
jobs:
  generate-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate package-lock.json
        run: |
          npm install --package-lock-only

      - name: Commit lockfile
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package-lock.json
          git commit -m "Add package-lock.json"
          git push
